include env.mk

.PHONY: all build bootloader kernel lbt stage install install-man uninstall clean test clippy qemu esp sign

all: build

build: bootloader kernel lbt

bootloader:
	CARGO_TARGET_DIR=$(CURDIR)/target cargo build --locked --target $(UEFI_TARGET) --profile $(PROFILE)

kernel:
	$(MAKE) -C kernel TARGET=$(UEFI_TARGET) PROFILE=$(PROFILE) build

# Host-side companion tool (`lbt`), explicitly not a default member so the
# UEFI-only `cargo build`/`clippy` above never try to compile it. Pure Rust:
# the boot-manager TUI is a ratatui/crossterm app, no embedded Python/cps.
lbt:
	CARGO_TARGET_DIR=$(CURDIR)/target \
	cargo build --locked --target $(RUST_TARGET) -p lbt --profile $(PROFILE)

# Stage a ready-to-boot ESP tree under build/esp with the UEFI-canonical boot
# file name for this architecture plus the EFI-stub kernel at its path under
# \EFI\leon\. Only needs bootloader + kernel: `lbt` is not part of the ESP.
stage: bootloader kernel
	mkdir -p $(ESP)/EFI/BOOT $(ESP)/EFI/leon
	install -m 644 $(BL_EFI) $(ESP)/EFI/BOOT/$(BOOT_FILE)
	install -m 644 $(KERNEL_EFI) $(ESP)/EFI/leon/kernel.efi

# Install onto a mounted ESP (e.g. `make install DESTDIR=/mnt/esp`). The EFI
# tree goes at the ESP root (boot files must sit in \EFI\BOOT); only host-side
# artifacts (man pages) use the $(PREFIX) convention.
install: stage install-man
	install -d $(DESTDIR)/EFI/BOOT $(DESTDIR)/EFI/leon
	install -m 644 $(BL_EFI) $(DESTDIR)/EFI/BOOT/$(BOOT_FILE)
	install -m 644 $(KERNEL_EFI) $(DESTDIR)/EFI/leon/kernel.efi

install-man:
	install -d $(DESTDIR)$(PREFIX)/share/man/man1 $(DESTDIR)$(PREFIX)/share/man/man7
	install -m 644 docs/lbt.1 docs/lbl.1 $(DESTDIR)$(PREFIX)/share/man/man1/
	install -m 644 docs/leon-common.7 $(DESTDIR)$(PREFIX)/share/man/man7/

uninstall:
	rm -f $(DESTDIR)/EFI/BOOT/$(BOOT_FILE) $(DESTDIR)/EFI/leon/kernel.efi
	rm -f $(DESTDIR)$(PREFIX)/share/man/man1/lbt.1 $(DESTDIR)$(PREFIX)/share/man/man1/lbl.1 $(DESTDIR)$(PREFIX)/share/man/man7/leon-common.7

# Generic host test run: the host-testable workspace crates (`common`, `lbt`)
# with default features. The `leon` UEFI binary is excluded — a `#![no_main]`
# EFI application has no host test harness — and no target/feature flags are
# hard-coded here.
test:
	CARGO_TARGET_DIR=$(CURDIR)/target cargo test --locked --workspace --exclude leon

clippy:
	cargo clippy --all-targets --target $(UEFI_TARGET) -- -D warnings
	$(MAKE) -C kernel TARGET=$(UEFI_TARGET) clippy
	CARGO_TARGET_DIR=$(CURDIR)/target cargo clippy -p lbt -- -D warnings

qemu: stage
	ARCH=$(ARCH) ./scripts/run_qemu.sh

esp: stage
	ARCH=$(ARCH) ./scripts/make_esp.sh

# Sign the staged ESP tree in place with the Secure Boot key set generated by
# `scripts/sign.sh setup` (keys/). Re-run after every rebuild of the loader or
# kernel. Enrollment instructions: docs/secure-boot.md.
sign: stage
	./scripts/sign.sh sign-all

clean:
	cargo clean
	$(MAKE) -C kernel clean
	rm -rf build
