//! Boot entry discovery and persistence.
//!
//! On every boot, lbl scans the ESP for every `\EFI\<vendor>\*.efi` file — the
//! same convention the firmware's own Boot Manager uses — and treats each one
//! as a boot entry. Nothing is hardcoded: Leon's own kernel is no longer
//! special, it lives at `\EFI\leon\kernel.efi` and is chainloaded exactly like
//! any other entry with `LoadImage`/`StartImage`.
//!
//! The discovered entries are written to a JSONC file on the boot volume
//! (configurable via the `entries_file` boot config key, default
//! `\EFI\leon\entries.jsonc`) so host tooling (`lbt list`) sees exactly what a
//! boot found. Writing is best-effort; the in-memory discovery is the source
//! of truth for the menu.

use alloc::string::String;
use alloc::vec::Vec;

use uefi::cstr16;
use uefi::data_types::CStr16;
use uefi::fs::{FileSystem, Path};
use uefi::{CString16, Char16};

use leon_common::boot_config::BootConfig;

/// Root of every vendor directory on the ESP.
pub const EFI_ROOT: &CStr16 = cstr16!(r"\EFI");
/// Firmware fallback directory — contains this same loader on many ESPs.
const BOOT_DIR: &CStr16 = cstr16!("BOOT");
/// Default entries file path, relative to the boot volume root.
const DEFAULT_ENTRIES_FILE: &CStr16 = cstr16!(r"\EFI\leon\entries.jsonc");
/// Directory that always holds the entries file, so it can be created up front.
const LEON_DIR: &CStr16 = cstr16!(r"\EFI\leon");

/// One boot entry: a UEFI application on the ESP.
pub struct Entry {
    /// Display label (also what `default_entry` matches against).
    pub label: CString16,
    /// Absolute ESP path, `\EFI\...`.
    pub path: CString16,
}

/// Discovers every `*.efi` under `\EFI\<vendor>\`, in directory-then-name
/// order. The firmware fallback directory is skipped so the loader itself
/// never shows up as a boot entry.
pub fn discover(fs: &mut FileSystem) -> Vec<Entry> {
    let mut entries = Vec::new();
    let Ok(iter) = fs.read_dir(Path::new(EFI_ROOT)) else {
        return entries;
    };
    for item in iter.flatten() {
        if !item.is_directory() {
            continue;
        }
        let vendor = item.file_name();
        if eq_ignore_ascii_case(vendor, BOOT_DIR) {
            continue;
        }
        let Some(dir_path) = join_path(EFI_ROOT, vendor) else {
            continue;
        };
        let Ok(sub) = fs.read_dir(Path::new(dir_path.as_ref())) else {
            continue;
        };
        for file in sub.flatten() {
            if !file.is_regular_file() || !ends_with_efi(file.file_name()) {
                continue;
            }
            let name = file.file_name();
            let Some(full) = join_path(&dir_path, name) else {
                continue;
            };
            entries.push(Entry {
                label: CString16::from(name),
                path: full,
            });
        }
    }
    entries
}

/// Writes the discovered entries to the configured JSONC file on the boot
/// volume. Best-effort: a read-only volume never derails the boot.
pub fn write_entries_file(fs: &mut FileSystem, cfg: &BootConfig, entries: &[Entry]) {
    let Some(path) = entries_path(cfg) else {
        return;
    };
    if fs.create_dir_all(Path::new(LEON_DIR)).is_err() {
        return;
    }
    let _ = fs.write(Path::new(path.as_ref()), entries_json(entries).as_bytes());
}

/// Resolves the entries file path from the boot config, defaulting to
/// `\EFI\leon\entries.jsonc`.
fn entries_path(cfg: &BootConfig) -> Option<CString16> {
    match &cfg.entries_file {
        Some(path) => CString16::try_from(path.as_str()).ok(),
        None => Some(CString16::from(DEFAULT_ENTRIES_FILE)),
    }
}

/// Renders the entries list as a JSONC document:
///
/// ```jsonc
/// // Auto-generated by lbl on every boot. Do not edit.
/// {
///   "entries": [
///     { "label": "kernel.efi", "path": "\\EFI\\leon\\kernel.efi" }
///   ]
/// }
/// ```
fn entries_json(entries: &[Entry]) -> String {
    let mut out = String::from("// Auto-generated by lbl on every boot. Do not edit.\n");
    out.push_str("{\n  \"entries\": [\n");
    for (i, e) in entries.iter().enumerate() {
        out.push_str("    { ");
        out.push_str("\"label\": \"");
        out.push_str(&json_escape(&cstr_lossy(e.label.as_ref())));
        out.push_str("\", \"path\": \"");
        out.push_str(&json_escape(&cstr_lossy(e.path.as_ref())));
        out.push_str("\" }");
        if i + 1 < entries.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("  ]\n}\n");
    out
}

/// Escapes a string for inclusion in a JSON string literal.
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

/// Case-insensitive `\EFI`-style path builder: `parent \ name`, NUL-terminated.
pub fn join_path(parent: &CStr16, name: &CStr16) -> Option<CString16> {
    let mut v = Vec::with_capacity(parent.to_u16_slice().len() + 1 + name.to_u16_slice().len() + 1);
    v.extend_from_slice(parent.to_u16_slice());
    v.push(b'\\' as u16);
    v.extend_from_slice(name.to_u16_slice());
    v.push(0);
    CString16::try_from(v).ok()
}

/// ASCII case-insensitive comparison of two UEFI strings.
pub fn eq_ignore_ascii_case(a: &CStr16, b: &CStr16) -> bool {
    let a = a.to_u16_slice();
    let b = b.to_u16_slice();
    a.len() == b.len()
        && a.iter()
            .zip(b)
            .all(|(x, y)| ascii_lower(*x) == ascii_lower(*y))
}

/// Whether a UEFI file name ends in `.efi` (any case).
pub fn ends_with_efi(name: &CStr16) -> bool {
    const SUFFIX: [u16; 4] = [b'.' as u16, b'e' as u16, b'f' as u16, b'i' as u16];
    let name = name.to_u16_slice();
    name.len() >= SUFFIX.len()
        && name[name.len() - SUFFIX.len()..]
            .iter()
            .zip(SUFFIX)
            .all(|(x, y)| ascii_lower(*x) == y)
}

/// Lowercases an ASCII code unit; leaves everything else unchanged.
fn ascii_lower(c: u16) -> u16 {
    if (b'A' as u16..=b'Z' as u16).contains(&c) {
        c + (b'a' as u16 - b'A' as u16)
    } else {
        c
    }
}

/// Lossy UTF-16 to UTF-8, for logging and JSON output only.
pub fn cstr_lossy(c: &CStr16) -> String {
    c.to_u16_slice()
        .iter()
        .map(|&u| char::from_u32(u as u32).unwrap_or('?'))
        .collect()
}

/// Appends a decimal `u32` to a UTF-16 string (menu countdown).
pub fn push_u32(s: &mut CString16, mut n: u32) {
    let mut digits = [0u8; 10];
    let mut i = digits.len();
    while n > 0 {
        i -= 1;
        digits[i] = (n % 10) as u8 + b'0';
        n /= 10;
    }
    if i == digits.len() {
        s.push(Char16::try_from('0').expect("'0' is a valid Char16"));
        return;
    }
    for &d in &digits[i..] {
        s.push(Char16::try_from(d as char).expect("ASCII digit is a valid Char16"));
    }
}
